version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - ./Data_remote/zookeeper_data/zk-data:/var/lib/zookeeper/data
      - ./Data_remote/zookeeper_data/zk-txn-logs:/var/lib/zookeeper/log
    user: root
    container_name: proyectoshop-zookeeper-1_remote
    networks:
      - proyectoshop_default_remote

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - '${PORT_KAFKA_HOST}:${PORT_KAFKA_HOST}'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:${PORT_KAFKA_HOST}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
    depends_on:
      - zookeeper
    volumes:
      - ./Data_remote/kafka_data:/var/lib/kafka/data
    user: root
    container_name: proyectoshop-kafka-1_remote
    networks:
      - proyectoshop_default_remote

  producer_scrapy:
    image: chasen64/scrapingshop:10.0.0
    shm_size: '2g'
    env_file:
      - .env
    container_name: proyectoshop-producer_scrapy-1_remote
    networks:
      - proyectoshop_default_remote
  
  consumer_productos:
    image: chasen64/consumersshop:5.0.0
    shm_size: '2g'
    env_file:
      - .env
    container_name: proyectoshop-consumer_productos-1_remote
    networks:
      - proyectoshop_default_remote

  db_mysql:
    image: mysql:8.1.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ejemplo
      MYSQL_USER: usuario
      MYSQL_PASSWORD: ejemplo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Data_remote/mysql_data:/var/lib/mysql
    container_name: proyectoshop-db_mysql-1_remote
    networks:
      - proyectoshop_default_remote

  consumer_mysql:
    image: chasen64/consumermysqlshop:4.0.0
    shm_size: '2g'
    env_file:
      - .env
    container_name: proyectoshop-consumer_mysql-1_remote
    networks:
      - proyectoshop_default_remote

  consumer_url:
    image: chasen64/consumermysqlshopurl:1.0.0
    shm_size: '2g'
    env_file:
      - .env
    container_name: proyectoshop-consumer_url-1_remote
    networks:
      - proyectoshop_default_remote

networks:
  proyectoshop_default_remote: {}